# Generated by Django 4.2.11 on 2026-04-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("period_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="symptomlog",
            name="bloating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="symptomlog",
            name="breast_tenderness",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="symptomlog",
            name="flow",
            field=models.CharField(default="None", max_length=20),
        ),
        migrations.AlterField(
            model_name="symptomlog",
            name="cramps",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="symptomlog",
            name="fatigue",
            field=models.BooleanField(default=False),
        ),
    ]
