# Generated by Django 6.0.3 on 2026-04-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('family_history', models.BooleanField()),
                ('lump', models.BooleanField()),
                ('pain', models.BooleanField()),
                ('size_change', models.BooleanField()),
                ('nipple_discharge', models.BooleanField()),
                ('skin_change', models.BooleanField()),
                ('smoking', models.BooleanField()),
                ('alcohol', models.BooleanField()),
                ('physical_activity', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
